version: 2
updates:
  - package-ecosystem: npm
    directory: /msp-tenant-monitoring/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      frontend-dependencies:
        patterns:
          - "*"
