# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auditlogs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uditlogs.proto\x12\tAuditLogs\"\x9d\x01\n\nip_address\x12-\n\x02\x61\x66\x18\x01 \x01(\x0e\x32!.AuditLogs.ip_address.addr_family\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\x0c\"R\n\x0b\x61\x64\x64r_family\x12\x16\n\x12\x41\x44\x44R_FAMILY_UNSPEC\x10\x00\x12\x14\n\x10\x41\x44\x44R_FAMILY_INET\x10\x01\x12\x15\n\x11\x41\x44\x44R_FAMILY_INET6\x10\x02\"3\n\x0c\x61udit_stream\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\x12\x15\n\rdetailed_data\x18\x02 \x01(\t\"\xf6\x02\n\x14\x61udit_stream_message\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\r\x12\x10\n\x08group_id\x18\x03 \x01(\x11\x12\x0e\n\x06target\x18\x04 \x01(\t\x12(\n\tclient_ip\x18\x05 \x01(\x0b\x32\x15.AuditLogs.ip_address\x12\x10\n\x08username\x18\x06 \x01(\t\x12\x15\n\rcustomer_name\x18\x07 \x01(\t\x12\x16\n\x0e\x63lassification\x18\x08 \x02(\t\x12\x13\n\x0b\x64\x65vice_type\x18\t \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12\x10\n\x08\x61pp_name\x18\x0b \x01(\t\x12\x0e\n\x06msp_id\x18\x0c \x01(\t\x12\x13\n\x0bhas_details\x18\r \x01(\x08\x12\x0f\n\x07\x64\x65tails\x18\x0e \x03(\t\x12\x0e\n\x06header\x18\x0f \x01(\t\x12\'\n\x06others\x18\x10 \x01(\x0b\x32\x17.AuditLogs.audit_stream')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auditlogs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IP_ADDRESS._serialized_start=31
  _IP_ADDRESS._serialized_end=188
  _IP_ADDRESS_ADDR_FAMILY._serialized_start=106
  _IP_ADDRESS_ADDR_FAMILY._serialized_end=188
  _AUDIT_STREAM._serialized_start=190
  _AUDIT_STREAM._serialized_end=241
  _AUDIT_STREAM_MESSAGE._serialized_start=244
  _AUDIT_STREAM_MESSAGE._serialized_end=618
# @@protoc_insertion_point(module_scope)
