# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='location.proto',
  package='Location',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0elocation.proto\x12\x08Location\"\x1b\n\x0bmac_address\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\x0c\"\xe9\x03\n\x0fstream_location\x12\x16\n\x0esta_location_x\x18\x01 \x01(\x02\x12\x16\n\x0esta_location_y\x18\x02 \x01(\x02\x12\x13\n\x0b\x65rror_level\x18\x03 \x01(\r\x12\x1a\n\x12hashed_sta_eth_mac\x18\x07 \x01(\t\x12\x14\n\x0cgeofence_ids\x18\x08 \x03(\t\x12*\n\rloc_algorithm\x18\t \x01(\x0e\x32\x13.Location.algorithm\x12\x11\n\tlongitude\x18\x0b \x01(\x01\x12\x10\n\x08latitude\x18\x0c \x01(\x01\x12\x10\n\x08\x61ltitude\x18\r \x01(\x01\x12(\n\x04unit\x18\x0e \x01(\x0e\x32\x1a.Location.measurement_unit\x12*\n\x0bsta_eth_mac\x18\x0f \x02(\x0b\x32\x15.Location.mac_address\x12\x18\n\x10\x63\x61mpus_id_string\x18\x10 \x01(\t\x12\x1a\n\x12\x62uilding_id_string\x18\x11 \x01(\t\x12\x17\n\x0f\x66loor_id_string\x18\x12 \x01(\t\x12\x43\n\x0btarget_type\x18\x13 \x01(\x0e\x32\x19.Location.target_dev_type:\x13TARGET_TYPE_UNKNOWN\x12\x12\n\nassociated\x18\x14 \x01(\x08*o\n\x0ftarget_dev_type\x12\x17\n\x13TARGET_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13TARGET_TYPE_STATION\x10\x01\x12\x13\n\x0fTARGET_TYPE_TAG\x10\x02\x12\x15\n\x11TARGET_TYPE_ROGUE\x10\x03*\x94\x01\n\talgorithm\x12\x1b\n\x17\x41LGORITHM_TRIANGULATION\x10\x00\x12\x1a\n\x16\x41LGORITHM_AP_PLACEMENT\x10\x01\x12\x19\n\x15\x41LGORITHM_CALIBRATION\x10\x02\x12\x18\n\x14\x41LGORITHM_ESTIMATION\x10\x03\x12\x19\n\x15\x41LGORITHM_LOW_DENSITY\x10\x04*4\n\x10measurement_unit\x12\n\n\x06METERS\x10\x00\x12\x08\n\x04\x46\x45\x45T\x10\x01\x12\n\n\x06PIXELS\x10\x02')
)

_TARGET_DEV_TYPE = _descriptor.EnumDescriptor(
  name='target_dev_type',
  full_name='Location.target_dev_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TARGET_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TARGET_TYPE_STATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TARGET_TYPE_TAG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TARGET_TYPE_ROGUE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=549,
  serialized_end=660,
)
_sym_db.RegisterEnumDescriptor(_TARGET_DEV_TYPE)

target_dev_type = enum_type_wrapper.EnumTypeWrapper(_TARGET_DEV_TYPE)
_ALGORITHM = _descriptor.EnumDescriptor(
  name='algorithm',
  full_name='Location.algorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALGORITHM_TRIANGULATION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALGORITHM_AP_PLACEMENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALGORITHM_CALIBRATION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALGORITHM_ESTIMATION', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALGORITHM_LOW_DENSITY', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=663,
  serialized_end=811,
)
_sym_db.RegisterEnumDescriptor(_ALGORITHM)

algorithm = enum_type_wrapper.EnumTypeWrapper(_ALGORITHM)
_MEASUREMENT_UNIT = _descriptor.EnumDescriptor(
  name='measurement_unit',
  full_name='Location.measurement_unit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METERS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIXELS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=813,
  serialized_end=865,
)
_sym_db.RegisterEnumDescriptor(_MEASUREMENT_UNIT)

measurement_unit = enum_type_wrapper.EnumTypeWrapper(_MEASUREMENT_UNIT)
TARGET_TYPE_UNKNOWN = 0
TARGET_TYPE_STATION = 1
TARGET_TYPE_TAG = 2
TARGET_TYPE_ROGUE = 3
ALGORITHM_TRIANGULATION = 0
ALGORITHM_AP_PLACEMENT = 1
ALGORITHM_CALIBRATION = 2
ALGORITHM_ESTIMATION = 3
ALGORITHM_LOW_DENSITY = 4
METERS = 0
FEET = 1
PIXELS = 2



_MAC_ADDRESS = _descriptor.Descriptor(
  name='mac_address',
  full_name='Location.mac_address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='Location.mac_address.addr', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_STREAM_LOCATION = _descriptor.Descriptor(
  name='stream_location',
  full_name='Location.stream_location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sta_location_x', full_name='Location.stream_location.sta_location_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sta_location_y', full_name='Location.stream_location.sta_location_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_level', full_name='Location.stream_location.error_level', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hashed_sta_eth_mac', full_name='Location.stream_location.hashed_sta_eth_mac', index=3,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geofence_ids', full_name='Location.stream_location.geofence_ids', index=4,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc_algorithm', full_name='Location.stream_location.loc_algorithm', index=5,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Location.stream_location.longitude', index=6,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Location.stream_location.latitude', index=7,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Location.stream_location.altitude', index=8,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='Location.stream_location.unit', index=9,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sta_eth_mac', full_name='Location.stream_location.sta_eth_mac', index=10,
      number=15, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='campus_id_string', full_name='Location.stream_location.campus_id_string', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='building_id_string', full_name='Location.stream_location.building_id_string', index=12,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floor_id_string', full_name='Location.stream_location.floor_id_string', index=13,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_type', full_name='Location.stream_location.target_type', index=14,
      number=19, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='associated', full_name='Location.stream_location.associated', index=15,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=547,
)

_STREAM_LOCATION.fields_by_name['loc_algorithm'].enum_type = _ALGORITHM
_STREAM_LOCATION.fields_by_name['unit'].enum_type = _MEASUREMENT_UNIT
_STREAM_LOCATION.fields_by_name['sta_eth_mac'].message_type = _MAC_ADDRESS
_STREAM_LOCATION.fields_by_name['target_type'].enum_type = _TARGET_DEV_TYPE
DESCRIPTOR.message_types_by_name['mac_address'] = _MAC_ADDRESS
DESCRIPTOR.message_types_by_name['stream_location'] = _STREAM_LOCATION
DESCRIPTOR.enum_types_by_name['target_dev_type'] = _TARGET_DEV_TYPE
DESCRIPTOR.enum_types_by_name['algorithm'] = _ALGORITHM
DESCRIPTOR.enum_types_by_name['measurement_unit'] = _MEASUREMENT_UNIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mac_address = _reflection.GeneratedProtocolMessageType('mac_address', (_message.Message,), dict(
  DESCRIPTOR = _MAC_ADDRESS,
  __module__ = 'location_pb2'
  # @@protoc_insertion_point(class_scope:Location.mac_address)
  ))
_sym_db.RegisterMessage(mac_address)

stream_location = _reflection.GeneratedProtocolMessageType('stream_location', (_message.Message,), dict(
  DESCRIPTOR = _STREAM_LOCATION,
  __module__ = 'location_pb2'
  # @@protoc_insertion_point(class_scope:Location.stream_location)
  ))
_sym_db.RegisterMessage(stream_location)


# @@protoc_insertion_point(module_scope)
