# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esecurity.proto\x12\x08Security\"\x1a\n\nMacAddress\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x02(\x0c\"s\n\x14RapidsStreamingEvent\x12\x0f\n\x07\x63ust_id\x18\x01 \x02(\t\x12#\n\x05rogue\x18\x02 \x03(\x0b\x32\x14.Security.RogueEvent\x12%\n\x08idsEvent\x18\x03 \x03(\x0b\x32\x13.Security.WIDSEvent\"\xab\x02\n\nRogueEvent\x12&\n\x08rogue_id\x18\x01 \x02(\x0b\x32\x14.Security.MacAddress\x12\x16\n\x0e\x63lassification\x18\x02 \x02(\r\x12\x12\n\nfirst_seen\x18\x03 \x01(\t\x12\x11\n\tlast_seen\x18\x04 \x01(\t\x12\x12\n\nrogue_name\x18\x05 \x01(\t\x12\x0c\n\x04ssid\x18\x06 \x01(\t\x12\x0f\n\x07lan_mac\x18\x07 \x01(\t\x12\x18\n\x10\x66irst_det_device\x18\x08 \x01(\t\x12\x17\n\x0flast_det_device\x18\t \x01(\t\x12\x12\n\nencryption\x18\n \x01(\r\x12\x0c\n\x04port\x18\x0b \x01(\t\x12\x1a\n\x12\x63ontainment_status\x18\x0c \x01(\t\x12\x12\n\nmac_vendor\x18\r \x01(\t\"\xd2\x01\n\tWIDSEvent\x12\x11\n\tdevice_id\x18\x01 \x02(\t\x12\x14\n\x0c\x65vent_number\x18\x02 \x02(\r\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x13\n\x0b\x61ttack_type\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65tected_ap\x18\x06 \x01(\t\x12&\n\x08mac_addr\x18\x07 \x01(\x0b\x32\x14.Security.MacAddress\x12\x12\n\nradio_band\x18\x08 \x01(\t\x12\r\n\x05level\x18\t \x01(\t*)\n\x06\x41\x63tion\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\n\n\x06UPDATE\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=688
  _ACTION._serialized_end=729
  _MACADDRESS._serialized_start=28
  _MACADDRESS._serialized_end=54
  _RAPIDSSTREAMINGEVENT._serialized_start=56
  _RAPIDSSTREAMINGEVENT._serialized_end=171
  _ROGUEEVENT._serialized_start=174
  _ROGUEEVENT._serialized_end=473
  _WIDSEVENT._serialized_start=476
  _WIDSEVENT._serialized_end=686
# @@protoc_insertion_point(module_scope)
