# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streaming.proto',
  package='StreamMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fstreaming.proto\x12\rStreamMessage\"a\n\x08MsgProto\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x13\n\x0b\x63ustomer_id\x18\x05 \x01(\t\x12\x0e\n\x06msp_id\x18\x06 \x01(\tb\x06proto3')
)




_MSGPROTO = _descriptor.Descriptor(
  name='MsgProto',
  full_name='StreamMessage.MsgProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='StreamMessage.MsgProto.subject', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='StreamMessage.MsgProto.data', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='StreamMessage.MsgProto.timestamp', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='StreamMessage.MsgProto.customer_id', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msp_id', full_name='StreamMessage.MsgProto.msp_id', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['MsgProto'] = _MSGPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgProto = _reflection.GeneratedProtocolMessageType('MsgProto', (_message.Message,), dict(
  DESCRIPTOR = _MSGPROTO,
  __module__ = 'streaming_pb2'
  # @@protoc_insertion_point(class_scope:StreamMessage.MsgProto)
  ))
_sym_db.RegisterMessage(MsgProto)


# @@protoc_insertion_point(module_scope)
