Campus AP: CAMPUS_AP
Micro Branch AP: MICROBRANCH_AP
Access Switch: ACCESS_SWITCH
Core Switch: CORE_SWITCH
Aggregation Switch: AGG_SWITCH
Mobility GW: MOBILITY_GW
Branch GW: BRANCH_GW
Bridge: BRIDGE
Hybrid NAC: HYBRID_NAC
